### ISSUE TITLE
Crash in EFILoader

### ISSUE THREAD

**Issue by alexander-pick** [binarly-io/efiXplorer#3]
I am experiencing a crash trying to load an EFI firmware into IDA with the latest version. I compiled the module for Linux and Windows and tried the precompiled version as well all with the same result. I also tried IDA 7.4 and 7.5 for comparison without success. The module crashes IDA during analysis, IDA simply closes itself and creates a dmp. 

Now I am a bit unsure what the best way to report this, I can provide the EFI image which I am trying to load if this helps.

**Comment by alexander-pick** [comment]
[R70.zip](https://github.com/binarly-io/efiXplorer/files/5386748/R70.zip)

It is a complete EFI firmware image with lot of modules. The loader parses it to a certain point and than IDA closes itself. The file is attached above.

**Comment by matrosov** [comment]
Thank you for the bug submission. We will investigate this problem.

**Comment by yeggor** [comment]
Tested on the latest version, everything works (efiXloader + efiXplorer).
![R70_010600](https://user-images.githubusercontent.com/22826617/116948618-8c0b1b80-ac88-11eb-8f6c-6a24dd963476.PNG)
