### ISSUE TITLE
Problems with duplicated GUIDs

### ISSUE THREAD

**Issue by assafcarlsbad** [binarly-io/efiXplorer#38]
Hi,

I recently encountered an SMM image that for some reason had two copies of `EFI_SMM_BASE2_PROTOCOL_GUID`. As can be seen in the image below, `efiXplorer` renamed the first object to `EFI_SMM_BASE2_PROTOCOL_GUID` and the second to `EFI_SMM_BASE2_PROTOCOL_GUID`_**0**. 
![image](https://user-images.githubusercontent.com/8438963/160029483-9f828546-92c5-4f19-b1cb-4859dd862466.png)

Later, `EFI_SMM_BASE2_PROTOCOL_GUID`_**0** is passed to `LocateProtocol` but `efiXplorer` doesn't set the type of the corresponding interface (`qword_1E498`). Is it caused by the "non-standard" protocol name?
![image](https://user-images.githubusercontent.com/8438963/160029870-cb13cf46-23fe-4302-8920-f68e184961a4.png)

Attached is the problematic binary.
[NvramSmm.zip](https://github.com/binarly-io/efiXplorer/files/8346439/NvramSmm.zip)

Thanks!

**Comment by yeggor** [comment]
Hello. I've just checked version from master, it seems to be working for me.
You may need to refresh the pseudocode with F5 (or refresh the pseudocode and perform rescan).
<img width="756" alt="Screenshot 2022-03-25 at 03 34 18" src="https://user-images.githubusercontent.com/22826617/160032667-207658c5-b02b-4705-8ac9-e142c18ea0cb.png">

**Comment by yeggor** [comment]
@assafcarlsbad
btw, efiXplorer now names child SW SMI handlers `ChildSwSmiHandler` instead of `SmiHandler`.
So you should probably fix it here: https://github.com/Sentinel-One/brick/blob/12e4172c2a1ae92252f8cca763374926a3b1411f/brick/ida/modules/efiXplorer/efiXplorer.py#L23

**Comment by assafcarlsbad** [comment]
Just verified it, the `master` build indeed fixes this issue.
And thanks for the heads up regarding the name change!
