### ISSUE TITLE
efiXplorer 4.1 not work with ida pro 7.7 

### ISSUE THREAD

**Issue by cifamcg** [binarly-io/efiXplorer#46]
[autohidden] efiXplorer: guids.json file not found, copy "guids" directory to <IDA_DIR>/plugins
[efiXplorer] guids.json file not found, copy "guids" directory to <IDA_DIR>/plugins

**Comment by matrosov** [comment]
A copy of GUID's json file should be placed in <IDA_DIR>/plugins. 
Download the guids.json file here: [https://github.com/binarly-io/efiXplorer/releases/download/4.1/guids.zip](https://github.com/binarly-io/efiXplorer/releases/download/4.1/guids.zip)
