### ISSUE TITLE
Improperly closing the file lead double-free crash.

### ISSUE THREAD

**Issue by cc-crack** [binarly-io/efiXplorer#52]
Hi,
When I tested in the ida 7.7 linux environment, I found that the efixloader would crash in some cases.
I checked the code and found that load_file closes the li pointer passed in externally and reuses it, but ida closes this pointer again after load_file completes.
I've submitted a PR to fix this.

**Comment by yeggor** [comment]
Hello, thank you. I've merged your PR.
