### ISSUE TITLE
Runtime Services

### ISSUE THREAD

**Issue by rithien** [binarly-io/efiXplorer#6]
Hi
Some models have more than one pointers to boot services table and runtime services
![Obraz 03 05 2021, godz  23 33](https://user-images.githubusercontent.com/987300/116936327-f95a8480-ac67-11eb-892e-bc08b30d2a04.jpg)

**Comment by yeggor** [comment]
Hello, actually the plugin tries to find all possible variables with gBS, gRT addresses, but there are always edge cases. Could you share a binary file?

**Comment by rithien** [comment]
[Fujitsu_Lifebook_N532.BIN.zip](https://github.com/binarly-io/efiXplorer/files/6419753/Fujitsu_Lifebook_N532.BIN.zip)
