### ISSUE TITLE
Prebuilt binaries for macOS are x86-only

### ISSUE THREAD

**Issue by NikolajSchlej** [binarly-io/efiXplorer#68]
Tried using efiXplorer with arm64 build of IDA, and it failed to load due to incompatible plugin architectures:
```
dlopen(/Applications/IDA Pro 7.7/ida64.app/Contents/MacOS/plugins/efiXplorer64.dylib): dlopen(/Applications/IDA Pro 7.7/ida64.app/Contents/MacOS/plugins/efiXplorer64.dylib, 0x0002): tried: '/Applications/IDA Pro 7.7/ida64.app/Contents/MacOS/plugins/efiXplorer64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/IDA Pro 7.7/ida64.app/Contents/MacOS/plugins/efiXplorer64.dylib' (no such file), '/Applications/IDA Pro 7.7/ida64.app/Contents/MacOS/plugins/efiXplorer64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Applications/IDA Pro 7.7/ida.app/Contents/MacOS/plugins/efiXplorer64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/IDA Pro 7.7/ida.app/Contents/MacOS/plugins/efiXplorer64.dylib' (no such file), '/Applications/IDA Pro 7.7/ida.app/Contents/MacOS/plugins/efiXplorer64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
/Applications/IDA Pro 7.7/ida64.app/Contents/MacOS/plugins/efiXplorer64.dylib: can't load file
```

**Comment by yeggor** [comment]
Thank you. I've fixed `CMakeLists.txt` to build universal binaries. You can download the latest builds of `efiXplorer.dylib` and `efiXplorer64.dylib` here: https://github.com/binarly-io/efiXplorer/actions/runs/3174878351

**Comment by NikolajSchlej** [comment]
Tested the resulting binaries, efiXplorer works as expected, but efiXLoader fails to load because it lacks ```EFIDecompress```:
```
dlopen(/Applications/IDA Pro 7.7/ida64.app/Contents/MacOS/loaders/efiXloader64.dylib): dlopen(/Applications/IDA Pro 7.7/ida64.app/Contents/MacOS/loaders/efiXloader64.dylib, 0x0002): symbol not found in flat namespace '_EfiDecompress'
/Applications/IDA Pro 7.7/ida64.app/Contents/MacOS/loaders/efiXloader64.dylib: can't load file
```

Looks like the library dependencies need another arch too.

**Comment by NikolajSchlej** [comment]
```
if(APPLE)
  # to build Mach-O universal binaries with 2 architectures
  set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} "-fPIC -arch x86_64 -arch arm64")
else()
  set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} "-fPIC")
endif()
```
This is most likely what causes the issue here: ```CMAKE_C_FLAGS``` also need to be set to the same values, otherwise the will not be applied to .C files.

**Comment by yeggor** [comment]
Thanks, it works for me: https://github.com/binarly-io/efiXplorer/actions/runs/3175159507
Can you check please on your setup?

**Comment by NikolajSchlej** [comment]
Nope, still doesn't work for some reason, investigating.

**Comment by yeggor** [comment]
I originally put in the wrong link, then corrected it. Maybe that's the reason?

**Comment by NikolajSchlej** [comment]
```
nschlej@Nikolajs-MBP ~ % objdump --arch=x86_64 --syms efiXloader64.dylib | grep Decompress
0000000000031860 l     F __TEXT,__text _LzmaDecompress
0000000000037860 l     F __TEXT,__text _Decompress
0000000000037c70 l     F __TEXT,__text _EfiDecompress
0000000000037cc0 l     F __TEXT,__text _TianoDecompress
00000000000a86c0 l     F __TEXT,__text __Z14gzipDecompressRK10UByteArrayRS_
nschlej@Nikolajs-MBP ~ % objdump --arch=arm64 --syms efiXloader64.dylib | grep Decompress
000000000007fd24 l     F __TEXT,__text __Z14gzipDecompressRK10UByteArrayRS_
0000000000000000         *UND* _EfiDecompress
0000000000000000         *UND* _LzmaDecompress
0000000000000000         *UND* _TianoDecompress
```
This is how you can verify that symbols are present in the final binary without loading it.

**Comment by NikolajSchlej** [comment]
That's more like it:
```
nschlej@Nikolajs-MBP ~ % objdump --arch=arm64 --syms ~/Downloads/efiXloader64.dylib | grep Decompress 
000000000002e494 l     F __TEXT,__text _LzmaDecompress
000000000003420c l     F __TEXT,__text _Decompress
0000000000034624 l     F __TEXT,__text _EfiDecompress
0000000000034674 l     F __TEXT,__text _TianoDecompress
0000000000096af0 l     F __TEXT,__text __Z14gzipDecompressRK10UByteArrayRS_
```

**Comment by yeggor** [comment]
> That's more like it:
> 
> ```
> nschlej@Nikolajs-MBP ~ % objdump --arch=arm64 --syms ~/Downloads/efiXloader64.dylib | grep Decompress 
> 000000000002e494 l     F __TEXT,__text _LzmaDecompress
> 000000000003420c l     F __TEXT,__text _Decompress
> 0000000000034624 l     F __TEXT,__text _EfiDecompress
> 0000000000034674 l     F __TEXT,__text _TianoDecompress
> 0000000000096af0 l     F __TEXT,__text __Z14gzipDecompressRK10UByteArrayRS_
> ```

For me it looks the same (for `1c71dc70fa1073229b8f806e5ab3fa61e882d6192764639a36f8de563086eb8a  efiXloader64.dylib`). And works fine.

**Comment by NikolajSchlej** [comment]
IDA stopped complaining, but the loader is still not listed in the obvious place. Do I need to do something else for it to show up?
<img width="881" alt="Screenshot 2022-10-03 at 23 09 30" src="https://user-images.githubusercontent.com/1845688/193683062-bfc37ba9-9c93-48ed-880e-c4fdeb1661ec.png">

**Comment by yeggor** [comment]
EFI modules must be opened with the standard loader (`pe64.dylib` in your case).
But the full firmware image (which we can open with UEFITool) can be opened with `efiXloader64.dylib`.
<img width="618" alt="image" src="https://user-images.githubusercontent.com/22826617/193683730-907fd251-49fd-41c1-be59-06566132e374.png">

**Comment by yeggor** [comment]
After it is loaded, you can also run the efiXplorer plugin and scan the whole image

**Comment by Lichtlos** [comment]
I've compiled plugins and loader as universal binaries with idasdk 8.0 for M1/M2 macs

[macos-fat.zip](https://github.com/binarly-io/efiXplorer/files/9718483/macos-fat.zip)
