### ISSUE TITLE
efiXplorer does not work in IDA9.0

### ISSUE THREAD

**Issue by LordCasser** [binarly-io/efiXplorer#90]
efiXplorer does not work in IDA 9.0 beta.

**Comment by yeggor** [comment]
Hi, the version compatible with both IDA 8.4 and IDA 9.0 (RC1 beta release) can be found here: https://github.com/binarly-io/efiXplorer/tree/rc1.

**Comment by LordCasser** [comment]
> Hi, the version compatible with both IDA 8.4 and IDA 9.0 (RC1 beta release) can be found here: https://github.com/binarly-io/efiXplorer/tree/rc1.

thinks about that work
