### ISSUE TITLE
Crash at Arm fixOffsets()

### ISSUE THREAD

**Issue by gandalf4a** [binarly-io/efiXplorer#93]
When I tested arm UEFI as the attachment `AcpiTableDxe.efi` , both PEI and DXE modes crashed and generates a mini-dump, when executing fixOffsets(). How to deal with this problem? 
```
System: Windows 11 22631.4169
IDA pro: 8.3.230608 Windows x64
efiXplorer: v6.0
```

**Comment by gandalf4a** [comment]
[AcpiTableDxe.zip](https://github.com/user-attachments/files/17281526/AcpiTableDxe.zip)

**Comment by yeggor** [comment]
Hi. I see that you are using IDA 83 when latest version of efiXplorer was not compatible with it. I made it compatible and fixed some issues I didn't notice during the big change when updating the plugin and porting it to IDA 90.

Could you please use the latest version from master:

```
python3 build.py build-plugin ~/sdk/83/idasdk83 --hexrays_sdk ~/sdk/83/hexrays_sdk
```

I've tested your test case with IDA 83 and newer versions of IDA and can confirm that it's working:

<img width="1406" alt="image" src="https://github.com/user-attachments/assets/d186e1a9-2f0f-4051-b9a4-9679a33f9c1a">

As for the crash in `fixOffsets()` (which is now `fix_offsets()`), I can't see how this is possible. I guess it can only happen if the sdk and IDA version are incompatible. Please note that you'll have to build efixplorer with corresponding sdk.

**Comment by gandalf4a** [comment]
Thanks for compatibility with ida83. I used the master version to compile through, and did not crash, but no matter the PEI or DXE module will appear unresponded pop-up window:
![image](https://github.com/user-attachments/assets/dd0bff87-5ac2-4e1c-b3f7-19cc97610cb1)
What is the cause of this situation? My cpu and memory usage are only about 40%.  I don't think it's due to poor hardware performance.
![image](https://github.com/user-attachments/assets/bc47e20c-083f-4eb8-b7cb-02a6ffa9eaac)

**Comment by yeggor** [comment]
could you share binary on which you catched this? Maybe somewhere we didn't make an early return and it went unnoticed during testing (as arm support was tested much weaker than x86)

**Comment by yeggor** [comment]
I've added potential fix (which might affect analysis for DXE modules). Сould you check please? And still share the binary or firmware if possible?

**Comment by gandalf4a** [comment]
The firmware I tested was the same as the attachments above ‘AcpiTableDxe.efi’. 
Here's what I compiled the master（https://github.com/binarly-io/efiXplorer/commit/ef4d5e17560ae39417b5e2ce8b9a1a775d710d56) with the 83sdk, and I just added msg output to some functions to figure out what went wrong:
[efiXplorer64.zip](https://github.com/user-attachments/files/17288745/efiXplorer64.zip)
Below is a picture of me executing other efi files, as follows:
[ArmCpuDxe.zip](https://github.com/user-attachments/files/17288814/ArmCpuDxe.zip)
You can see that there is still no response when the fix_Offsets function is executed:
![image](https://github.com/user-attachments/assets/9aa00492-371f-4cc8-8dca-8874e8bcf416)

**Comment by gandalf4a** [comment]
I added some msg output to fix_offsets() like this:
![image](https://github.com/user-attachments/assets/5c6f4e5d-42e1-4dfe-8470-9d3100aab6ac)
As you can see from the ida output, you should be stuck in a while loop and unable to exit, losing response.
![image](https://github.com/user-attachments/assets/f89de889-c31f-49da-a9db-cdec05645b4c)

**Comment by gandalf4a** [comment]
I made a mistake, not losing the response at fix_offsets(), but at fix_offsets(). 

Here's what I tested by adding some msg：
![image](https://github.com/user-attachments/assets/addb84df-faf3-427d-af9e-bfcb14f74b67)

You can see that it executes into the for loop and the following code is unresponsive:
```
    set_name(ep, "_ModuleEntryPoint", SN_FORCE);
#ifdef HEX_RAYS
    efi_hexrays::track_entry_params(get_func(ep), 0);
#endif /* HEX_RAYS */
```

![image](https://github.com/user-attachments/assets/83af5426-609f-44c6-ba8c-49715ea5d618)

**Comment by gandalf4a** [comment]
I made sure to use the hexrays sdk.

However, this item is not displayed when cmake is configured.
![image](https://github.com/user-attachments/assets/ca177789-890c-49f2-841b-0ac64ca5091d)

Did it not work?

**Comment by gandalf4a** [comment]
A close examination of the compiled output below shows that hexrays_sdk does indeed refer to it.

![image](https://github.com/user-attachments/assets/78de9c85-9454-49ef-81ee-e08613eb7826)

In addition, I commented out the above line of code, but the plugin execution still loses response when other hexrays_sdk functions are executed.

There are about a dozen plug-ins in my ida, but they are not implemented. Will this affect me?

**Comment by gandalf4a** [comment]
I tested IDA 9.0 version and didn't encounter any unresponsive bugs, which should mean there's something wrong with my 8.3 version. I can close this issue. 

However, I encountered two errors while compiling the 9.0 version, which I fixed by following the instructions provided.
```
/home/gandalf/test/005-idapython/efiXplorer/efiXplorer/efi_utils.cc: In function ‘ea_list_t efi_utils::search_protocol(std::string)’:
/home/gandalf/test/005-idapython/efiXplorer/efiXplorer/efi_utils.cc:621:9: error: ‘bin_search’ was not declared in this scope; did you mean ‘bin_search3’?
  621 |         bin_search(start, BADADDR, bytes, nullptr, 16, BIN_SEARCH_FORWARD);
      |         ^~~~~~~~~~
      |         bin_search3
/home/gandalf/test/005-idapython/efiXplorer/efiXplorer/efi_utils.cc: In function ‘ea_list_t efi_utils::find_data(ea_t, ea_t, uchar*, size_t)’:
/home/gandalf/test/005-idapython/efiXplorer/efiXplorer/efi_utils.cc:850:15: error: ‘bin_search’ was not declared in this scope; did you mean ‘bin_search3’?
  850 |     auto ea = bin_search(start, end_ea, data, nullptr, len, BIN_SEARCH_FORWARD);
      |               ^~~~~~~~~~
      |               bin_search3
```

**Comment by xorpse** [comment]
The compilation errors you have for IDA 9.0 are due to differences between the beta SDK and release SDK (Hex-Rays renamed the `bin_search` API to `bin_search3` in 9.0 RC1). You should update your IDA installation and SDK to the latest version.

**Comment by yeggor** [comment]
I agree with @xorpse. For IDA 90 we only support the latest released version (and corresponding sdk), and `bin_search3` was used in beta versions prior to RC1. I'm closing the issue. Feel free to reopen it if you will have any other related issues that we can help you with.
